data:
  batch_size: 8
  trim_prob: 0.9
  trim_min: 0.5
  balanced_sampling: True
model:
  latent: 32
  encode:
    inproj_size: 7
    inproj_stride: 4
    inproj_norm: True
    hidden: 64
    kernel_size: 5
    stride: 2
    stride_on: all
    layers: 2
    depth_variant: True
    outproj_size: 64
    leak: 0.0
    dropout: 0.0
    layer_norm: True
  decode:
    hidden: 64
    kernel_size: 5
    stride: 2
    stride_on: all
    layers: 2
    depth_variant: True
    outproj_size: 5
    leak: 0.1
    dropout: 0.0
    layer_norm: True
  kl_coeff: 0.1
train:
  epochs: 100
  lr: 0.001
  weight_decay: 0.01
