data:
  batch_size: 32
  trim_prob: 0.9
  trim_min: 0.5
  balanced_sampling: True
model:
  type: resnet
  inproj_size: 7
  inproj_stride: 4
  inproj_norm: True
  hidden: 64
  kernel_size: 5
  stride: 2
  stride_on: all
  layers: 2
  outproj_size: 64
  leak: 0.0
  dropout: 0.2
  batch_norm: True
train:
  epochs: 150
  lr: 0.001
  weight_decay: 0.01
