data:
  batch_size: 8
  trim_prob: 0.9
  val_augments: 5
  trim_min: 0.5
  balanced_sampling: True
model:
  type: rnn
  cell_type: lstm
  hidden: 64
  layers: 2
  bidirectional: True
  outproj_size: 64
  outproj_leak: 0.0
  dropout: 0.2
train:
  epochs: 200
  lr: 0.001
  weight_decay: 0.01
