name: pscrnn
dependencies:
  - python=3.8
  - colorama=0.4
  - conda-forge::omegaconf=2.0.6
  - cudatoolkit=10.2
  - numpy=1.19
  - pandas=1.2
  - pytorch::pytorch=1.8
  - requests=2.25
  - scipy=1.6
  - tqdm=4.59
