name: pscrnn
dependencies:
  - python=3.8
  - conda-forge::hydra-core=1.0
  - conda-forge::pytorch-lightning=1.1
  - numpy=1.19
  - pandas=1.2
  - pytorch::pytorch=1.7
  - requests=2.25
  - scipy=1.5
