hydra:
  run:
    dir: outputs/ae/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/ae/${now:%Y-%m-%d}/${now:%H-%M-%S}
data:
  batch_size: 16
  trim_prob: 0.0
  trim_min: 0.5
  balanced_sampling: False
model:
  latent: 64
  inproj_size: 8
  inproj_stride: 4
  enc_hidden: 32
  enc_kernel_size: 5
  enc_stride: 2
  enc_layers: 2
  enc_depth_variant: True
  enc_leak: 0.0
  enc_dropout: 0.0
  enc_weight_norm: True
  enc_layer_norm: True
  dec_hidden: 32
  dec_kernel_size: 5
  dec_stride: 2
  dec_layers: 2
  dec_depth_variant: True
  dec_leak: 0.2
  dec_dropout: 0.0
  dec_weight_norm: True
  dec_layer_norm: True
  outproj_size: 5
  lr: 0.001
  weight_decay: 0.01
train:
  max_epochs: 100
