defaults:
  - trans: identity
  - model: prnn
  - optim: adam
  - sched: warmup_exponential
data:
  batch_size: 32
loss: cross_entropy
early_stop:
  patience: 15
train:
  gpus: 1
train_hparam:
  gradient_clip_val: 1.0
