defaults:
  - inproj: conv
  - optim: adam
  - sched: exponential
data:
  batch_size: 64
  spectrogram: False
  spec_nperseg: 64
  spec_noverlap: 32
model:
  n_hidden: 32
  dropout: 0.0
  input_dropout: 0.0
  loss_type: cross_entropy
  init_gate_bias: 1.0
early_stop:
  patience: 30
trainer:
  gpus: 1
