# @package _group_
_target_: pscrnn.classify.ConvPrnnClassify
n_hidden: 32
dropout: 0.0
input_dropout: 0.0
inproj_size_h: 2
inproj_size_w: 4
inproj_stride_h: 1
inproj_stride_w: 2
init_gate_bias: 1.0
kernel_size: 5
